site_name: Projecte Intermodular 2DAW
site_url: https://pi-2n.github.io/PI-Laravel/  
use_directory_urls: false

nav:
  - "1️⃣ Inicio": "index.md"

  - "2️⃣ Sprints":
      - "Sprint 1": "sprints/sprint1.md"
      - "Sprint 2": "sprints/sprint2.md"
      - "Sprint 3": "sprints/sprint3.md"
      - "Sprint 4": "sprints/sprint4.md"
      - "Sprint 5": "sprints/sprint5.md"
      - "Sprint 6": "sprints/sprint6.md"

  - "3️⃣ Documentación":
      - "Diagrama de Gantt": "diagrama_gantt.pdf"
      - "Riesgos":
          - "Individuales": "riesgos/riesgos_individuales.md"
          - "Plan de prevención": "riesgos/prevencion_riesgos.md"
      - "Sostenibilidad": "sostenibilidad/sostenibilidad.md"

theme:
  language: es
  favicon: imagenes/letters_logo.png
  name: "material"
  palette:
    - scheme: default
      primary: orange
      accent: deep-orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Canviar a mode nit
    - scheme: slate
      primary: orange
      accent: deep-orange
      toggle:
        icon: material/toggle-switch
        name: Canviar a mode dia
  font:
    text: Roboto
    code: Roboto Mono
  logo: "imagenes/letters_logo.png"
  features:
    - header.autohide
    - toc.integrate
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.code.annotate

extra:
  search:
    language: "es"
  analytics:
    provider: google
    property: G-X6D0LR7TC8

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - footnotes
  - meta
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3

copyright: 2025-2026  Adrián Gutiérrez Galvañ, Alejandro Rico Sánchez - Licencia CC BY-NC-SA